### ISSUE TITLE
Scope-tracking should apply to template parameters as well

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/google-modes#22]
e.g. in Java,

```java
class Foo {
  void <X> foo(X x, Y y) {
  }
}
```

the second usage of X should have different CSS classes set than the usage of Y.

**Comment by marijnh** [comment]
So you want scope tracking for type/template variables as well? That's going to take some rethinking, so I'm going to have to put that off until after my holiday (more generally, I'm going to have to take a break on the immediately-fixing of these issues, since I'm traveling for the remainder of the week).

**Comment by mtaran-google** [comment]
Yes, that was in the contract as well.

It's not very time-critical, though, so doing it later is fine.

**Comment by marijnh** [comment]
Attached patches change the C++ and Java modes to highlight type parameters as `"type def"`, and uses of these as `"type local"`. Does that work for you?

**Comment by mtaran-google** [comment]
Yes, I believe that should. I'll try it out over the next few days to make sure and reopen (or file a new issue) if anything.
