### ISSUE TITLE
[cc] indentation inside of lambda inconsistent depending on whether the parameter list is wrapped

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/google-modes#241]
if you press enter at the end of the second `{` in

```cc
int main() {
  return Foo([variablenumber1, variablenumber2, variablenumber3, variablenumber4, var5]() {    
  });
}
```

the indentation is +4, but if you do it in 

```cc
int main() {
  return Foo([variablenumber1, variablenumber2, variablenumber3, variablenumber4, 
             var5]() {    
  });
}
```

the indentation becomes +15. but ideally what happens inside the argument list shouldn't affect the indentation inside the body of the lambda, similar to how it works in normal functions/methods.

**Comment by marijnh** [comment]
It is behaving that way due to a condition added for #110, where you indicate that being part of an argument list _should_ cause the lambda body to be indented more for the list. The way this works is a bit messy right now, but let's first look into the desired behavior—should a lambda body in an argument list be +2 from the body around it, or +2 from the indentation that you'd get when continuing the argument list?

**Comment by mtaran-google** [comment]
Ah, I see! I think it's best to leave the logic as it is (re #110).

However, actually the original reported bug was about this kind of related situation:

```cc
int main() {
  return Foo([variablenumber1, variablenumber2, variablenumber3, variablenumber4, 
             var5]() {
    // foo
  });
}
```

Where the user has (for reasons) decided to use a lesser indentation in the comment, but then after pressing enter at the end of the comment, got the indentation prescribed by the (further away) `{` rather than following the indentation that the closer-by comment already adhered to. Would it be possible for the more immediately preceding comment to supply the indentation in this type of case? I can't think of a case off the top of my head where line comments come at a different indentation level than what's supposed to go after them.

**Comment by marijnh** [comment]
> Would it be possible for the more immediately preceding comment to supply the indentation in this type of case?

Hm, that's rather fundamentally not how this indenter works (it looks at the parent construct, not siblings, to figure out a desired indentation—the way the parser is modeled, it doesn't even have access to the way siblings were parsed).

Attached patch makes it so that the indentation in this case is computed relative to the line that starts the lambda, rather than the line that starts its parameter list, which should at least cover this case. Shall we close this or look further into the idea of aligning statements to nearby lines?

**Comment by mtaran-google** [comment]
Thanks for the fix! I think we can close this for now and I'll circle back if we get any more user reports of this sort of thing.
