### ISSUE TITLE
[py] stack overflow with a large number of varying lines in an array.

### ISSUE THREAD

**Issue by takamori** [codemirror/google-modes#280]
Repros with a large enough array of the form

```py
foo = [
   "some content",
   "different content",
   // .....(more varying content)...
   "last line"
]
```

The call stack overflow occurs in a `StateClass.matchNext` (in grammar mode code, in mode.js) recursion which appears to be one stack frame per line in the array.

Repros when the following is added to the script for the demo page. The number of lines needed for repro will depend on the specs of the machine that is being used to run the demo. Note that this will **not** repro if the content is simply pasted into the page, interestingly enough. It will repro if the content is in the `textarea` before constructing the CodeMirror instance, though.

```js
  var lines = [];
  lines.push('foo = [');
  for (var i =0; i < 30000; i++) {
      lines.push('  "line ' + i + ' here",');
  }
  lines.push('  "last line"');
  lines.push(']');
  var content = lines.join('\n');
  editors['python'].setValue(content);
```

**Comment by takamori** [comment]
also, it does not repro if lineWrapping is set to true in the CodeMirror config.

**Comment by marijnh** [comment]
The `lineWrapping` thing led me on a wonderful wild goose chase, but seems incidental (you can reproduce it by making some edits in a line-wrapped editor as well, it just happened sooner due to the change in the current longest line triggering the update differently).

The issue was that comma-expression rules were written in a way where the part after the comma was parsed as another expression, which consumed the next comma, and so on, growing the stack for each comma. Attached patches fix this in the Python and JavaScript (which had the issue too) modes.
