### ISSUE TITLE
[cpp] problems with lambdas etc.

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/google-modes#71]
```cpp
static string f(X* x, int length) {
  string result(length, '\0');
  foo([&]() {
    int i = 0;
    return bar(*x);
  });
  return result;
}
```

sorry this combines a bunch of issues into one...

1. newline after the second { produces too much indentation
1. if you delete the `int i = 0` line, the first `return` changes color
1. `result` is not highlighted as a variable def/usage

**Comment by marijnh** [comment]
The problem isn't related to the lambda, but rather to the declaration about it -- `string result(length, '\0');`. Since this, all the way to the quote, looks exactly like a function declaration, my grammar couldn't disambiguate it and gets confused. Attached patch works around that and solves these issues.
